# Generated by Django 5.2.1 on 2025-05-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('judul_video', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Uang',
            fields=[
                ('id_uang', models.AutoField(primary_key=True, serialize=False)),
                ('total_uang', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pemasukan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_pengeluaran', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id_catatan', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_uang', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waktu_tanggal', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('uang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.uang')),
            ],
        ),
        migrations.CreateModel(
            name='Menonton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pengguna')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.video')),
            ],
        ),
    ]
