# Generated by Django 5.2.1 on 2025-05-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catatan',
            name='keterangan',
            field=models.CharField(default='Tanpa keterangan', max_length=100),
        ),
    ]
